### ISSUE TITLE
KeyError: 'filename'

### ISSUE THREAD

**Issue by deepseek** [zhouyuangan/cv_toolboxes#1]
@zhouyuangan 
When running `python via2icdar15.py` I am getting error:
```
Traceback (most recent call last):
  File "via2icdar15.py", line 7, in <module>
    filename = info["filename"]
KeyError: 'filename'
```

**Comment by zhouyuangan** [comment]
The via version should be 2.0.8,check your version,please.

**Comment by deepseek** [comment]
@zhouyuangan I am using via 2.0.8
here is a sample:
[test1.zip](https://github.com/zhouyuangan/cv_toolboxes/files/3907157/test1.zip)
