### ISSUE TITLE
Convert multiple via to icdar, using a folder as an input

### ISSUE THREAD

**Issue by deepseek** [zhouyuangan/cv_toolboxes#2]
@zhouyuangan 
Add an option to use an input folder as an input, instead of a single file.
The input folder will have a combination of via json and jpd files.

**Comment by zhouyuangan** [comment]
Hi,I try to understand what you meant, is that both via json file and JPEG images in the same path?

**Comment by deepseek** [comment]
I meant, instead of converting 1 via json into icdar txt, I have many Via json files which I want to convert.
Adding an option to load all the Via json files in a folder as an input, would be great.

**Comment by zhouyuangan** [comment]
Got it! I will take your advice on hand once I have free time. Thank you again.
